version: "3.9"
services:
  enhancedocs:
    container_name: enhancedocs
    restart: always
    build:
      context: .
    volumes:
      - ./.enhancedocs/data:/data/enhancedocs
      - ./.enhancedocs/config:/etc/enhancedocs
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ENHANCEDOCS_ACCESS_TOKEN: ${ENHANCEDOCS_ACCESS_TOKEN}
      ENHANCEDOCS_API_KEY: ${ENHANCEDOCS_API_KEY}
    ports:
      - '8080:8080'
